jobs:
  - name: runSh-1
    type: runSh
    steps:
      - TASK:
        - script: echo "Ola!"
      - IN: trigger-beta

  - name: runSh-2
    type: runSh
    steps:
      - IN: runSh-1
      - TASK:
        - script: echo "Uber!"
      - IN: trigger-beta
  
  - name: nginx-apache-manifest
    type: manifest
    steps:
      - IN: nginx-image
      - IN: runSh-1
      - TASK: managed
        pull: false
      - IN: trigger-beta
